{% extends "base.phtml" %}
{% import "macros.phtml" as macros %}

{% block content %}
<div class="brochurePageContent">
    <div class="brochurePageSplitLeft">
        <div>
            {% if bookmark.image_file %}
            <div class="brochureSplitImage" style="background-image: url('{{ bookmark.image_file }}');"></div>
            {% else %}
            <div class="brochureSplitImage"></div>
            {% endif %}
        </div>
        <div>
            <a href="{{ bookmark.url }}" target="_blank" rel="noopener">
                <h2>{{ bookmark.title }}</h2>
            </a>
            <p>{{ bookmark.description }}</p>
        </div>
    </div>

    {% if user_logged_in %}
    <h2>Edit Bookmark</h2>
    <form action="/bookmark/{{ bookmark.id }}/" method="post">
        {{ macros.generateCSRFMarkup(csrf_token) }}
        <input type="hidden" name="bookmark_id" value="{{ bookmark.id }}" />

        <div class="formSection">
            <fieldset>
                <div>
                    <label for="title">
                        Title
                    </label>
                    <input type="text" id="title" name="title" value="{{ bookmark.title }}">
                </div>
                <div>
                    <label for="url">
                        URL
                    </label>
                    <input type="text" id="url" name="url" value="{{ bookmark.url }}">
                </div>
                <div>
                    <label for="description">
                        Description
                    </label>
                    <textarea name="description" id="description">{{ bookmark.description }}</textarea>
                </div>

                <div class="checkItem" style="margin-top: 7px;">
                    {% if bookmark.public %}
                    <input type="checkbox" name="public" id="public" value="1" checked>
                    {% else %}
                    <input type="checkbox" name="public" id="public" value="1">
                    {% endif %}
                    <label style="display: inline;" for="public">Public/Visible</label>
                </div>
            </fieldset>
        </div>

        <div class="action-bar" style="width: 100%;">
            <div class="action-bar-left">
            </div>
            <div class="action-bar-right">
                <button type="submit" name="action" value="delete">Delete</button>
                <button type="submit" name="action" value="update">Save</button>
            </div>
        </div>
    </form>
    {% endif %}
</div>
{% endblock %}
