{% extends "base.phtml" %}
{% import "macros.phtml" as macros %}

{% block content %}
<div class="microblogContainer">
    {% if user_logged_in %}
    <div>
        <form action="/" method="post">
            {{ macros.generateCSRFMarkup(csrf_token) }}
            <input type="hidden" name="action" value="savePost">

            <div class="microblogPost">
                <div class="microblogPostHeader">
                    <div class="microblogPostHeaderName">
                        <span style="font-weight: bold;">
                            <label for="post_text">New Post</label>
                        </span>
                    </div>
                    <div class="microblogPostHeaderDate">
                    </div>
                </div>

                <div class="microblogPostContent">
                    <textarea rows="4" style="width: 100%;" name="post_text" id="post_text" placeholder="Create a new post."></textarea>

                    <div class="checkItem" style="margin-top: 7px;">
                        <input type="checkbox" name="published" id="published" value="1" checked>
                        <label style="display: inline;" for="published">Published</label>
                    </div>

                    <div class="checkItem" style="margin-top: 7px;">
                        <input type="checkbox" name="public" id="public" value="1" checked>
                        <label style="display: inline;" for="public">Show in Feed</label>
                    </div>
                </div>

                <div class="action-bar" style="width: 100%;">
                    <div class="action-bar-left"></div>
                    <div class="action-bar-right">
                        <button type="submit">Post</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
    {% endif %}

    {% for post in posts %}
    <div class="microblogPost">
        <div class="microblogPostHeader">
            <div class="microblogPostHeaderName">
                <span style="font-weight: bold;">{{ post.user_object.full_name }}</span>
            </div>
            <div class="microblogPostHeaderDate">
                <a href="/post/{{ post.id }}/">{{ post.created|date("n/j/Y") }} at {{ post.created|date("g:i a") }}</a>
            </div>
        </div>

        <div class="microblogPostContent">
            <p>{{ post.post_text }}</p>
        </div>

        {% if post.wasEdited %}
        <div class="microblogPostEditedDate">
            Edited {{ post.updated|date("n/j/Y") }} at {{ post.updated|date("g:i a") }}
        </div>
        {% endif %}
    </div>
    {% endfor %}

    <div id="paginator" class="paginator tilesPaginator">
        {{ macros.generatePageListing(current_page, num_pages, page_list, "/", "") }}
    </div>
</div>
{% endblock %}